### ISSUE TITLE
Could you update BlenderSciViz on par with  Blender2.8+?

### ISSUE THREAD

**Issue by HakunanMatatat** [zeffii/BlenderSciViz#3]
Hi,zeffii,many scripts in BlenderSciViz is outdated.Could you please update it to Blender2.8+?Thank you.

**Comment by zeffii** [comment]
hi @HakunanMatatat 

this is not high on my todo list. Maybe if there's a particular example that you want but can't get working yourself in 2.8 then link it here, and i'll see

**Comment by HakunanMatatat** [comment]
hi @zeffii,I am a new learner.Many scripts have the following error.Thanx.

Traceback (most recent call last):
  File "\Text", line 42, in <module>
  File "\Text", line 37, in generate
AttributeError: 'bpy_prop_collection' object has no attribute 'link'
Error: Python script failed, check the message in the system console

```python
    scene = bpy.context.scene    
    scene.objects.link(obj)     #line37
    obj.select = True
    obj.show_bounds = True # optional
    generate(geometry_function, "PointCloud_Object")  #line42` 
```

**Comment by zeffii** [comment]
OK, please read the blog post here about the changes needed.

https://blenderscripting.blogspot.com/2019/01/blender-bpy-for-280.html
